version: "3.8"

volumes:
  mysql-data: {}
  web-sql:
  

networks:
  demo:
    name: demo
    driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    networks:
      - demo
    environment:
      MYSQL_DATABASE: "newdb"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - mysql-data:/var/lib/mysql