version: "3.8"

volumes:
  mysql-data: {}
  web-sql:
  postgres-data: {}
  test-data: {}
  test-ph-data: {}
  
networks:
  demo:
    name: demo
    driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    networks:
      - demo
    environment:
      MYSQL_DATABASE: "newdb"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - mysql-data:/var/lib/mysql
  
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    networks:
      - demo
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: mydb1
    volumes:
      - postgres-data:/var/lib/postgres

  PhIntegrationSql:
    image: ph-adapters
    container_name: phintegration
    restart: on-failure
    networks:
      - demo
    depends_on:
      - mysql
    environment:
      DATABASE_USERNAME: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_HOST: "mysql"
      DATABASE_SCHEMA: "newdb"
      PORT: 8085
      STAGE: "test"
    ports:
      - "8085:8085"
    volumes:
      - mysql-data:/var/lib/mysql:rw
  GraphicEditorWebServer:
    build: 
      context: .
      dockerfile: Dockerfile.GraphicEditor
    image: graphic-editor
    restart: on-failure
    networks:
      - demo
    depends_on:
      - mysql
    environment:
      DATABASE_USERNAME: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_HOST: "mysql"
      DATABASE_SCHEMA: "newdb"
      PORT: 8084
      STAGE: "test"
    ports:
      - "8084:8084"
    volumes:
      - mysql-data:/var/lib/mysql:rw

  PhIntegrationTests:
      build: 
        context: .
        dockerfile: Dockerfile.PhIntegrationTests
      image: ph-tests
      depends_on:
        - mysql
      environment:
        DATABASE_USERNAME: "root"
        DATABASE_PASSWORD: "root"
        DATABASE_HOST: "mysql"
        DATABASE_TYPE: "mysql"
        DATABASE_SCHEMA: "newdb"
        STAGE: "test"
      expose: 
        - "80"
      networks: 
        - demo
      volumes:
        - test-ph-data:/var/lib/
#  PhIntegrationSql:
#    image: ph
#    container_name: phintegration
#    restart: on-failure
#    environment:
#      PORT: 50202
#      DATABASE_USERNAME: "root"
#      DATABASE_PASSWORD: "root"
#      DATABASE_HOST: "mysql"
#      DATABASE_SCHEMA: "newdb"
#      STAGE: "test"
#      PORT: 8082
#    ports:
#      - "8082:8082"

  UnitTests:
    build: 
      context: .
      dockerfile: Dockerfile.UnitTests
    image: unit-tests
    container_name: unit-tests-container
    restart: on-failure
    