version: "3.8"

volumes:
  mysql-data: {}
  web-sql:
  postgres-data: {}
  

networks:
  demo:
    name: demo
    driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    networks:
      - demo
    environment:
      MYSQL_DATABASE: "newdb"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - mysql-data:/var/lib/mysql
  
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    networks:
      - demo
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: mydb1
    volumes:
      - postgres-data:/var/lib/postgres

  IntegrationTestsSql:
    build: 
      context: .
      dockerfile: Dockerfile.IntegrationTests
    image: test
    depends_on:
      - mysql
    restart: on-failure
    environment:
      DATABASE_USERNAME: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_HOST: "mysql"
      DATABASE_SCHEMA: "newdb"
      STAGE: "test"
    expose: 
      - "80"
    networks: 
      - demo

  WebApplicationMySql:
    image: web
    restart: on-failure
    networks:
      - demo
    depends_on:
      - mysql
    environment:
      DATABASE_USERNAME: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_HOST: "mysql"
      DATABASE_SCHEMA: "newdb"
      PORT: 8085
      STAGE: "test"
    ports:
      - "8085:8085"

#  PhIntegration:
#    build: 
#      context: .
#      dockerfile: Dockerfile.PhIntegration
#    image: ph-integration
#    restart: on-failure
#    networks:
#      - demo
#    depends_on:
#      - mysql
#    environment:
#      DATABASE_USERNAME: "root"
#      DATABASE_PASSWORD: "root"
#      DATABASE_HOST: "mysql"
#      DATABASE_SCHEMA: "newdb"
#      STAGE: "test"
#      PORT: 8081
#    ports:
#      - "8081:8081"

  GraphicEditorWebServer:
    build: 
      context: .
      dockerfile: Dockerfile.GraphicEditor
    image: graphic-editor
    restart: on-failure
    networks:
      - demo
    depends_on:
      - mysql
    environment:
      DATABASE_USERNAME: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_HOST: "mysql"
      DATABASE_SCHEMA: "newdb"
      STAGE: "test"
      PORT: 8082
    ports:
      - "8082:8082"

  UnitTests:
    build: 
      context: .
      dockerfile: Dockerfile.UnitTests
    image: unit-tests
    container_name: unit-tests-container
    restart: on-failure
