version: "3.8"

volumes:
  my-db:

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'newdb4'
        # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
        # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
        # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
        # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
        # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql/data
  Backend:
    build: 
      context: .
      dockerfile: Backend/Dockerfile
    image: stefan7/medbaytechback:latest-back
    depends_on:
      - db
    ports:
      - "5000:5000"

  WebApplication:
    build: 
      context: .
      dockerfile: WebApplication/Dockerfile
    image: stefan7/medbaytechweb:latest-web
    depends_on:
      - Backend
    expose: 
      - "3306"
    ports:
      - "3306:3306"