FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /app

COPY Backend/Backend.csproj Backend/
COPY WebApplication/WebApplication.csproj WebApplication/
COPY MedbayTech.WebIntegrationTests/MedbayTech.WebIntegrationTests.csproj MedbayTech.WebIntegrationTests/

RUN dotnet restore MedbayTech.WebIntegrationTests/MedbayTech.WebIntegrationTests.csproj
COPY . .

#FROM build AS publish
WORKDIR /app/Backend
ENV PATH $PATH:/root/.dotnet/tools
RUN dotnet tool install -g dotnet-ef --version 3.1.9
RUN dotnet ef migrations add Init

FROM build AS test
LABEL test=true

WORKDIR /app/MedbayTech.WebIntegrationTests
CMD ["dotnet", "test"]
