services:
  
  WebApplicationPostgres:
    image: stefan7/medbaytechweb:latest
    container_name: web
    restart: on-failure
    networks:
      - demo
    depends_on:
      - postgres
    environment:
      DATABASE_USERNAME: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_HOST: "postgres"
      DATABASE_TYPE: "postgres"
      DATABASE_SCHEMA: "mydb1"
      STAGE: "production"
      PORT: "8080"
    ports:
      - "8080:8080"
    volumes:
      - postgres-data:/var/lib/postgres:rw

  
