version: "3.8"

volumes:
  postgres-data: {}
  
networks:
  demo:
    name: demo
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    networks:
      - demo
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
      POSTGRES_DB: mydb1
    volumes:
      - postgres-data:/var/lib/postgres

  PhIntegrationTests:
      image: stefan7/test2
      container_name: ph_integration_tests
      restart: on-failure
      depends_on:
        - postgres
      environment:
        DATABASE_USERNAME: "user"
        DATABASE_PASSWORD: "user"
        DATABASE_HOST: "postgres"
        DATABASE_TYPE: "postgres"
        DATABASE_SCHEMA: "mydb1"
        STAGE: "test"
      expose: 
        - "80"
      networks: 
        - demo
      volumes:
      - postgres-data:/var/lib/postgres:rw