FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build

WORKDIR /app

COPY MedbayTech.Common/MedbayTech.Common.csproj MedbayTech.Common/
COPY MedbayTech.Pharmacies/MedbayTech.Pharmacies.csproj MedbayTech.Pharmacies/

RUN dotnet restore MedbayTech.Pharmacies/MedbayTech.Pharmacies.csproj

COPY . .

FROM build AS publish
WORKDIR /app/MedbayTech.Pharmacies

ENV PATH $PATH:/root/.dotnet/tools
RUN dotnet tool install -g dotnet-ef --version 3.1.9
RUN dotnet ef migrations add Init

WORKDIR /app
RUN dotnet publish MedbayTech.Pharmacies/MedbayTech.Pharmacies.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS runtime

RUN useradd -ms /bin/bash defaultuser
WORKDIR /app

COPY --from=publish /app/out .
EXPOSE 5005

CMD ASPNETCORE_URLS=http://*:$PORT dotnet MedbayTech.Pharmacies.dll
