FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /app

COPY Backend/Backend.csproj Backend/
COPY WebApplication/WebApplication.csproj WebApplication/
COPY WebApplicationIntegrationTests/WebApplicationIntegrationTests.csproj WebApplicationIntegrationTests/

RUN dotnet restore WebApplicationIntegrationTests/WebApplicationIntegrationTests.csproj


RUN apt-get update && apt-get upgrade -y && apt-get install -y nodejs npm
RUN npm install npm@latest -g
RUN npm install -g npm
RUN npm install

COPY . .

FROM build AS publish
WORKDIR /app/Backend
ENV PATH $PATH:/root/.dotnet/tools
RUN dotnet tool install -g dotnet-ef --version 3.1.9
RUN dotnet ef migrations add Init

FROM build AS test
LABEL test=true

WORKDIR /app/WebApplicationIntegrationTests
CMD ["dotnet", "test"]
