version: "3.8"

volumes:
  mysql_data: {}

services:
  Backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    image: aleksandarignjatijevic/backend:latest
    volumes:
      - mysql_data:/var/lib/mysql/data
    expose:
      - "80"
    ports:
      - "5100:80"

  WebApplication:
    build:
      context: .
      dockerfile: WebApplication/Dockerfile
    image: aleksandarignjatijevic/web-application:latest
    depends_on:
      - Backend
    expose:
      - "5000"
    ports:
      - "5000:5000"

  WebApplicationFrontend:
    build:
      context: .
      dockerfile: WebApplication/Dockerfile
    image: aleksandarignjatijevic/web-application-frontend:latest
    
  
