FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /app

COPY MedbayTech.Users/MedbayTech.Users.csproj MedbayTech.Users/
COPY MedbayTech.Appointment/MedbayTech.Appointment.csproj MedbayTech.Appointment/
COPY MedbayTech.PatientDocuments/MedbayTech.PatientDocuments.csproj MedbayTech.PatientDocuments/
COPY MedbayTech.Rooms/MedbayTech.Rooms.csproj MedbayTech.Rooms/
COPY MedbayTech.WebIntegrationTests/MedbayTech.WebIntegrationTests.csproj MedbayTech.WebIntegrationTests/

RUN dotnet restore MedbayTech.WebIntegrationTests/MedbayTech.WebIntegrationTests.csproj
COPY . .


FROM build AS test
LABEL test=true

WORKDIR /app/MedbayTech.WebIntegrationTests
CMD ["dotnet", "test"]
