version: "3.8"

volumes:
  mysql-data:
  #web-sql:

networks:
  demo:
    name: demo
    driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    networks:
      - demo
    environment:
      MYSQL_DATABASE: "newdb"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - mysql-data:/var/lib/mysql:rw


  PhIntegrationSql:
    image: ph
    container_name: phintegration
    restart: on-failure
    environment:
      PORT: 50202
      DATABASE_USERNAME: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_HOST: "mysql"
      DATABASE_SCHEMA: "newdb"
    ports:
      - "8091:50202"
    networks:
      - demo
    depends_on:
      - mysql