// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmacyIntegration.Model;

namespace PharmacyIntegration.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20201119232757_migration2")]
    partial class migration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PharmacyIntegration.Model.Pharmacy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("APIEndpoint")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("APIKey")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Pharmacies");

                    b.HasData(
                        new
                        {
                            Id = "Jankovic",
                            APIEndpoint = "jankovic.rs",
                            APIKey = "ID1APIKEYAAAA"
                        },
                        new
                        {
                            Id = "Liman",
                            APIEndpoint = "liman.li",
                            APIKey = "ID2APIKEYAAAA"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
