export const environment = {
  production: true,
  baseUrl: "https://medbaytech.herokuapp.com",
  fedback: 'api/feedback',
  allFeedback: 'allFeedback',
  updateFeedbackStatus: 'updateFeedbackStatus',
  createFeedback : 'createFeedback',
  survey: 'api/survey',
  allQuestions: 'allQuestions',
  createSurvey : 'createSurvey',
  prescription: 'api/prescription',
  report: 'api/examinationsurgery',
  allPrescriptions: 'allPrescriptions',
  allReports: 'allReports',
  registration : 'api/registration',
  patientRegistration : 'patientRegistration',
  doctor : 'api/doctor',
  searchDoctor : 'searchDoctor',
  medicalRecord : 'api/medicalRecord',
  prescriptionSimpleSearch : 'api/prescription',
  reportSimpleSearch : 'api/report',
  patient: 'api/patient',
  updatePatientStatus: 'updatePatientStatus',
  maliciousPatients: 'maliciousPatients',
  allSurveyableAppointments : 'allSurveyableAppointments',
  allOtherAppointments : 'allOtherAppointments',
  allCancelableAppointments : 'allCancelableAppointments',
  cancelAppointment : 'cancelAppointment',
  allSpecializations : 'api/specialization',
  doctorsBySpecialization : "specialization",
  appointments : 'api/appointment',
  availableStrategy : 'availableStrategy',
  availableStandard : 'available',
  scheduleAppointment : 'schedule'
};
