export const environment = {
  production: true,
  //baseUrl: "https://medbaytech.herokuapp.com",
  baseUrl: "http://localhost:53843",
  fedback: 'feedback',
  allFeedback: 'allFeedback',
  updateFeedbackStatus: 'updateFeedbackStatus',
  createFeedback : 'createFeedback',
  survey: 'survey',
  allQuestions: 'allQuestions',
  createSurvey : 'createSurvey',
  prescription: 'prescription',
  report: 'examinationsurgery',
  allPrescriptions: 'allPrescriptions',
  allReports: 'allReports',
  registration : 'registration',
  patientRegistration : 'patientRegistration',
  doctor : 'doctor',
  searchDoctor : 'searchDoctor',
  medicalRecord : 'medicalRecord',
  prescriptionSimpleSearch : 'prescription',
  reportSimpleSearch : 'report',
  patient: 'patient',
  updatePatientStatus: 'updatePatientStatus',
  maliciousPatients: 'maliciousPatients',
  allSurveyableAppointments : 'allSurveyableAppointments',
  allOtherAppointments : 'allOtherAppointments',
  allCancelableAppointments : 'allCancelableAppointments',
  cancelAppointment : 'cancelAppointment',
  allSpecializations : 'specialization',
  doctorsBySpecialization : "specialization",
  appointments : 'appointment',
  availableStrategy : 'availableStrategy',
  availableStandard : 'available',
  scheduleAppointment : 'schedule'
};
